name: Test container structure

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: deepsquads/base
  TAG: ${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup container structure test
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

      - name: Run container structure test
        run: |
          docker build -t deepsquads-base-test .
          container-structure-test test --image deepsquads-base-test --config tests.yaml
